### ISSUE TITLE
Offer some kind of replay mode from the History/action log

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1064]
Probably representing a lot of work, but some kind of visualization/replay mode of games could be quite a nice addition for people to improve and go over their games.

**Comment by Manuel-777** [comment]
I am discarding this one, not because it wont be implemented, but because its irrelevant to keep it open (same goes for #1063)

Replays is like the ultimate goal, most improvements and optimizations are done with replays in mind. I haven't gone too deep in it yet, but be sure i am trying!

#1063 is a hard one that is certainly a part of that plan. I will not do it now, but if I want to be able to playback a game it will be required at some point, and action logs will be the first place it lands.
