### ISSUE TITLE
Vault progress in economy

### ISSUE THREAD

**Issue by OdinFK** [Manuel-777/MTG-Arena-Tool#147]
It would be sweet if the relevant events (booster opening especially, but also ICRs) would show how much wild card progress they generated. Currently they show only Gold and Gems. Sure, the vault will probably be removed soon, but this should be almost trivial, and it would be nice to see this especially for booster packs.

**Comment by Manuel-777** [comment]
Sorry, but I will not be adding any more vault support than what you can see in economy. I dont want to add support to it simply because it will probably create conflicts with data and logs when its removed, and since it will be removed soon, its just a waste of time/efforts.

 Data is stored trough, so any other willing developer could do it without much troubles.
