### ISSUE TITLE
Deleted decks re-appearing in 'My Decks'

### ISSUE THREAD

**Issue by tbc1187** [Manuel-777/MTG-Arena-Tool#224]
There are two decks which currently re-appear some time after being deleted. The original deck no longer exists in MTGA, nor does any new deck with the same name.

Have not determined the exact trigger, but it seems to be related to logging in/out of the game; MTGA Arena Tool is running in the background the entire time.

**Comment by Manuel-777** [comment]
The deck tab works as follows;
You create a deck and it will be shown in the tab (static, you cant delete it because it is in MTGA)
You delete that deck and it will still be shown, but now you can delete it from Tool (A red like shows on the right side, you can hover to see the delete button)
Once deleted a deck may re-appear in "My Decks" if;
You close MTGA right after deleting it, close Tool, open tool again (without opening MTGA)
This last case is because tool will read the logs on startup and determine your deck was there at first, but was deleted later. So the old deck will reappear with the delete button until you start MTGA again and the logs dont have any trace of the old deck.
