### ISSUE TITLE
MTGAT is becoming increasingly slower

### ISSUE THREAD

**Issue by Xiaminou** [Manuel-777/MTG-Arena-Tool#26]
It now takes about 2 minutes to load up.
Switching to History takes at least 30 seconds, switching to Collection takes about 20 seconds.

**Comment by Manuel-777** [comment]
fixed in developement, commits [2f46de](https://github.com/Manuel-777/MTG-Arena-Tool/commit/2f46dedccc9cd6f610b06009857beb58e4bb2c5e) and [facd6b](https://github.com/Manuel-777/MTG-Arena-Tool/commit/facd6bf1728ff4bb683d5236a074f596b59e1b19), amongst others.

Latest pre-release version has this resolved:
[v2.0.21](https://github.com/Manuel-777/MTG-Arena-Tool/releases/tag/v2.0.21)

**Comment by Xiaminou** [comment]
Thank you, it's indeed much faster.
However I see that it's still loading the tabs every time you switch between them, would it be a good idea to cache what's already been loaded?
