### ISSUE TITLE
Export in a standard format

### ISSUE THREAD

**Issue by davidogren** [Manuel-777/MTG-Arena-Tool#28]
I was hoping that "Copy to Clipboard" would let me import my collection into MTGGoldfish or a similar tool. But there isn't enough information in what is copied to the clipboard. Any chance that you could update the feature to support one of these formats: https://www.mtggoldfish.com/help/import_formats ?

**Comment by Manuel-777** [comment]
Seems reasonable, Since there are many formats, wouldnt a standard .exe be better than .csv?
Like normally there is:
1 Bomat Courier
2 Scrapheap Scounger
.. and so on

**Comment by davidogren** [comment]
I'm far from an expert on the tools and formats. But I think the general gist of the problem is that 

`1 Duress`

is ambiguous. It could be Duress from Core 19 or it could be Duress from Ixalan. So it can't be imported. The simplest format (at least according to that doc) is MTG Studio whic would be

`Duress, XLN,1,No`

The "no" (for foil) is obviously pointless for Arena. But that would be easy to hack after the fact. The XLN vs M19 is trickier, however. I was debating writing a script to try and convert the format, but it would obviously have to make guesses about which set everything belonged to and since you have the actual data it seemed like it would be easier to just see if you could make it an official feature.

**Comment by Manuel-777** [comment]
Oh exporting in that format is doable for sure, I'm just wondering if it would be better to use standard txt format instead of csv, or which csv to choose from those. Appearently MTGO and MTGGoldfish have different format for example, and adding one export for each possible platform in csv might be too much to add. On the other hand txt is the web standard across sites like starcity, mtggoldfish, deckstats, and more, simply paste and the site will grab the best version in case it's not defined.

So, which would be better to support from the list? Is CSV a popular enough decklist format to use between platforms rather than plain old txt?

On the other hand .txt file export is the simplest and already done [here](https://github.com/Manuel-777/MTG-Arena-Tool/commit/a759bf70de43d9fe8c12177e49e61647f49569fe)

**Comment by davidogren** [comment]
Also, to be clear, I was looking to export the collection, not an individual deck.

**Comment by davidogren** [comment]
For what it's worth, I got the chance to look at your code and this was an easy change to implement myself. (I'm not going to submit a PR because I just replaced the existing format which is probably not the best long term approach.) So, I'd still like to see this as part of the app, but please don't have a sense of urgency on my behalf: I've scratched my own itch. Thanks for the app and the quick response.

**Comment by Manuel-777** [comment]
Oh please share the way you implemented, if it helps people using the app I would love to include it!

**Comment by ecyrbe** [comment]
If i may suggest something. Export format could be customisable in settings with a single line and pre-defined variables and the copy to clipboard functionnality .

Exemple for Arena format :

Export format : $CardCount $CardName ($SetId) $CardSetId

Exemple custom CSV format :

Export format : "$CardName";"$CardText";"$SetName";$CardCount

**Comment by jonathanjames30** [comment]
This! I believe there are two purposes.
1) Users want to export their decklist
2) Users want to export their Collection. 

For decklist export i think what you currently have will suffice. However for Collections, the export will need additional fields like Set Name (arguably the most important field). 

The suggestions by @ecyrbe and @davidogren are very good suggestions. I just wanted to comment and say that I am also looking forward to these enhancements as im sure a lot of other players are too. 

Also, great app, good work so far!
