### ISSUE TITLE
Cards left in deck overlay no longer shows correct information with newest update

### ISSUE THREAD

**Issue by ianelletson** [Manuel-777/MTG-Arena-Tool#296]
![image](https://user-images.githubusercontent.com/1207114/56867541-f0b18280-69ab-11e9-9a59-13f99c0d434f.png)
Percentages do not add up to 100%

![image](https://user-images.githubusercontent.com/1207114/56867545-fb6c1780-69ab-11e9-8601-8859f90c4fcf.png)
Not ordered by percent remaining descending

**Comment by lusbenjamin** [comment]
I can easily reproduce the issues with the percentages. 🤔 we may have had a feature regression in the Sample Size panel when we [migrated to the new interpreter engine](https://github.com/Manuel-777/MTG-Arena-Tool/commit/89a29572a81e73152b8666712fe0b0fa2c0b4f26#diff-9179d37aa838679c9dd3c54d801755f9).

The second issue with ordering by percent was fixed in https://github.com/Manuel-777/MTG-Arena-Tool/pull/286 and should ship with the next release.

**Comment by Manuel-777** [comment]
I can reproduce too, definitely broke the calculations on last update, will fix asap

**Comment by ianelletson** [comment]
Thank you very much for your hard work.
