### ISSUE TITLE
Windows Malware flagging

### ISSUE THREAD

**Issue by theksk** [Manuel-777/MTG-Arena-Tool#324]
Hola,

wanted to try this out, but it seems Windows is flagging it as Malware.
Any explaination to that?
I have read in the webs that this tool should only be reading Logfiled, and would do no "In memory-foo" so to say, so why would it get flagged then? :)

thanks!

**Comment by Manuel-777** [comment]
Hello!
It's because the app is not code singed (the certificates are rather expensive), nor white listed by AV software (hard to maintain if we constantly update), thus they flag it simply because they can't verify the author is trustworthy.
The tool does, indeed only read a file in the arena home path :)

Cheers!
