### ISSUE TITLE
Wrong date stamp, booster opening details and wildcard redemption

### ISSUE THREAD

**Issue by EdwardCYC** [Manuel-777/MTG-Arena-Tool#399]
Hello, yesterday on 27th May, I opened 4 booster packs and redeemed 3 wildcards. However, in the Economy section, it showed the date stamp as 1 January 1970, and 1 booster pack was opened and 1 wildcard was redeemed. I have uploaded an image below.

![image](https://user-images.githubusercontent.com/50830952/58449105-ae12cf80-813c-11e9-8c30-3d82048e1014.png)

**Comment by Manuel-777** [comment]
Pushing v2.6.1 to beta channel (can be enabled in settings), please let me know if it fixes the problem! (it will not be retroactive) @aroundightii

**Comment by EdwardCYC** [comment]
After enabling beta updates channel in settings, the date stamps, booster opening and redemption details are correct again. So far there are no mistakes after the change. Thanks.

**Comment by EdwardCYC** [comment]
The datestamps are wrong again for some items:

![image](https://user-images.githubusercontent.com/50830952/59400990-cb49ce00-8dcb-11e9-8072-7d3d481047eb.png)

I live in the future it seems.

**Comment by msteveb** [comment]
I think the problem is that it is not as simple as a one-to-one correspondence between log language and date format. For example, in Australia we use English and yet we have date format DD/MM/YY, however I see:

```
let dateLangs = {
  English: "M/dd/yyyy hh:mm:ss aa", //ex 5/28/2019 10:20:35 PM
```

Thus 12 Jun 2019 is interpreted as 6 Dec 2019 and 13 Jun 2019 is skipped as out of bounds.
The basic problem is WOTC using locale-specific formats in log files, but is it possible to use the current windows locale info to determine the date format?
