### ISSUE TITLE
Error parsing response (set_deck_tag)

### ISSUE THREAD

**Issue by DrFridolin** [Manuel-777/MTG-Arena-Tool#468]
Started getting this error message recently (using version 2.7.5) when I change a deck's archetype manually. Upon restarting the tool, the deck archetypes revert to their previous status and my manual changes are discarded every time.

**Comment by DrFridolin** [comment]
I'd happy to provide more info if there is anything useful I can gather on my end. Thanks!

**Comment by Manuel-777** [comment]
Actually im aware of this one!
The problem is we read the logs on startup, thus re-scan all games you played last session. When the re-scanning happens the deck archetype is also set automatically.

We should probably not overwrite match data that is already saved, or do so in a smart way (not change archetypes particularly)
