### ISSUE TITLE
Ability to change the window title bar color

### ISSUE THREAD

**Issue by ecyrbe** [Manuel-777/MTG-Arena-Tool#47]
With the new visual enhancements and the ability to change the window background (i use teferi for example) it would be great if we could also change the window title bar color from brown to anything we like.

**Comment by ecyrbe** [comment]
You could require the user to relaunch the app. no big deal if that makes it easier to code.

**Comment by Manuel-777** [comment]
Yes, What I meant is, it probably end up being 'unfriendly' for consumers like, if you dont know CSS , you might have to write your own CSS replacement script to be loaded. And if you just want to change the title bar color or the text color, It could end up being _very_ problematic, unless someone has done it before you.

I could see this being great if there was a huge community behind developing scripts/styles and such in the future. Right now I want to try make it as user-friendly as possible because I know not everyone has the knowledge or the time to make something like that.

But be sure I would love to add this. Customization is something I totally love and I would love if mtgatool could have as much of it as possible.
