### ISSUE TITLE
Opening the app disables (systemwide) "option + key" characters in macOS

### ISSUE THREAD

**Issue by garvamel** [Manuel-777/MTG-Arena-Tool#483]
I'm on a MacBook Pro (Retina, 13-inch, Late 2013) running macOS version 10.14.5. Tool version 2.8.0.

As the title, whenever I open the app, I can't use "option + key" to write special characters systemwide (it even prevents me from entering the email in this app). Normal operation is restored upon closing.

It's not critical, but I guess it's worthwhile to report it. Thank you for this great tool!

**Comment by garvamel** [comment]
I didn't notice the 2.8.1 was out, and it seems to work fine in this one.

**Comment by Manuel-777** [comment]
Cool! It still puzzles me as what could cause it, what version were you using before ?

**Comment by garvamel** [comment]
Just the 2.8.0.

There's this line in `window_overlay/overlay-process.js:113` which might have to do with it. I'll reopen if the issue combes back after a reboot or something. Thanks again!

`globalShortcut.register("Alt+" + (index + 1), () => {
        overlay.webContents.send("close", -1);
      });`

**Comment by Manuel-777** [comment]
I am reopening this as other users reported the same. Upon further investigation this is the expected behaviour of `globalShortcut.register`, which is the only way to trigger shortcuts when the app does not have focus. we should probably choose a less invading shortcut for these and allow for change in the future.
