### ISSUE TITLE
Server unreachable, try offline mode

### ISSUE THREAD

**Issue by donsdgr81** [Manuel-777/MTG-Arena-Tool#598]
I just downloaded the latest 2,10.3 update and I'm getting a "Server unreachable, try offline mode" error.

**Comment by AnnanFay** [comment]
The issue here seems to be that the error message is unclear.

It would be useful if the error message stated if the arena-tool server is down or if it's a local internet issue. Or, at least tell the user these are options.

In the case of an arena-tool server it should indicate this is completely *normal*.

Maybe update the error message to:

> Arena Tool cannot contact the server.
> Please check your internet connection in case it's a local issue.
> Sometimes the server goes down - it should be back in a couple hours.
> Use **offline-mode** until the server is back online. All your data will be recorded.

**Comment by Manuel-777** [comment]
The error is spawned by http-api.js (https://github.com/Manuel-777/MTG-Arena-Tool/blob/534dc12f12e2a4584d0e1f72d1f2003022f4b6e4/window_background/http-api.js#L368) when an error occurs in the client side, or when the connection fails. I agree we can add more details (like the specific error code), but this is usually not the server's fault unless its completely unreachable (server is 100% down, which does not happen so oftenly).
