### ISSUE TITLE
Allow for some online feature to be used anonymously

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#629]
This is probably an intentional choice, but not knowing about it, I prefer to ask through an issue: could this be something considered to allow for some online features (explore tab for example, or deck sharing) to be used anonymously (especially the first one as it's most likely read-only feature). I also don't know about what's supposed to be on the home page as, as for the explore tab, you just have a message stating you're offline and nothing else.

EDIT: To clarify, anonymously here being without account.

**Comment by Manuel-777** [comment]
This is intentional, I wanted to limit the amount of queries to the explore functions for performance and security. Currently the explore tabs contains filters and does aggregation queries which I am not comfortable with to allow publicly.

Obviously security and query speed has improved significantly since my first iteration of it, so its something that can be reviewed at this point, the [metagame page](https://mtgatool.com/metagame/) is a good example of it, altrough it does not contain any filters.

**Comment by Porkepix** [comment]
Depending on the number of filter possibilities, couldn't these be cached by something like Varnish (https://varnish-cache.org/) to greatly improve service performances without weighting too much on backend server?

(As an example, I checked the website during the win all the cards events, but yes only the global meta was visible. It can also be nice to have it for the metagame challenge for example. An utopia would even be to merge datas from every MTGA trackers, but considering that most if not every other tracker appart from this one are closed source, this is really an utopia: they would never make such thing possible I think :þ)
