### ISSUE TITLE
Combine cards with the same name

### ISSUE THREAD

**Issue by ianelletson** [Manuel-777/MTG-Arena-Tool#66]
Some cards, like the guildgates for example, have different arts but are otherwise identical. These could be combined to trim up the decklist view.
![image](https://user-images.githubusercontent.com/1207114/46919682-6cb42200-cfa8-11e8-8625-4fbee41fa187.png)

**Comment by Manuel-777** [comment]
Was only able to do it for the Overlay trough, other places had issues with things like wildcards left and missing cards (ie: a deck with 2 guildgates were you only have 4 of one and 2 of the other could show 2 missing when you actually had six in total)
this can be fixed by adding in the database grpIds for reprints but right now its too troublesome as it requires extra processing for simple things like loading a deck.
