### ISSUE TITLE
Splitcard links to scryfall are wrong

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#673]
When clicking in the application on a splitcard from anywhere, it should open it in scryfall as for any other card.

Problem is that it opens a URL like this one: `https://scryfall.com/card/grn/222/Connive%20//%20Concoct`. The ` // ` in the url is a problem; scryfall chosed to replace it by a simple dash, so that the correct url is `https://scryfall.com/card/grn/222/connive-concoct`.

It's possible to either fix this by either manually forcing a ` // ` replacement by a dash, either remove the last part of the url after the slash: indeed, after testing it, `https://scryfall.com/card/grn/222/` does work, and the website will automatically add the missing part with a redirection.

**Comment by Lego6245** [comment]
The issue is probably in `openScryfallCard`, the card name we store in the DB probably has this double slash so when we add it directly to the end of the URL we get this problem.

I'm curious about removing the card name though, sounds like a clean fix, but is there a gotcha? My understanding is that set name + collectors ID is a unique identifier, but I could be wrong.

**Comment by Manuel-777** [comment]
if using the collector's id alone works, lets do it :)
