### ISSUE TITLE
Login failed/not working - no notifications

### ISSUE THREAD

**Issue by stuhl232** [Manuel-777/MTG-Arena-Tool#71]
I signed up through your website, but was not logged into MTGA Tool on my computer. I quit and opened to try to sign in again, but the login screen does nothing when I enter my username and password. Button click does nothing and there is no notification or message indicating something is wrong.  No password reset and no email sent on registration. 

If you need a free and easy way to send programmatic email you can check out: https://paylite.net/communicate.html. I use to work for them and they provide 30,000 free emails ith a simple API.

**Comment by Manuel-777** [comment]
I think you just need to run MTGA to create a new output log. Let me know if that works!

About emails, I have the verification system implemented but disabled because the messages were ending in spam and it was slow. Also, at the moment it's not really needed since I have no use for emails to be real.
