### ISSUE TITLE
MTG-Arena-Tool Detected As Virus

### ISSUE THREAD

**Issue by EiriksHDD** [Manuel-777/MTG-Arena-Tool#721]
I was going to install this on Windows 10 x64 and defender blocked it as if it has a virus in it.

**Comment by Manuel-777** [comment]
Sorry about that one, we'll get the app ceritifed soon to avoid this

**Comment by rramstad833** [comment]
This problem is back, apparently, or the code has been corrupted.
Windows Defender claims MTG-Arena-Tool has this trojan
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fBomitag.D!ml&threatid=2147741007
Removing the program i.e. uninstall fixes the warning.
