### ISSUE TITLE
Match History does not show multiples of cards

### ISSUE THREAD

**Issue by oseparovic** [Manuel-777/MTG-Arena-Tool#84]
Version 2.1.15

After clicking on a game under the History tab the opponents history only shows one copy of each card including lands even though they've played multiples of each
![clipboard02](https://user-images.githubusercontent.com/3710226/47967767-0013cc80-e016-11e8-9500-870d9fc19b5f.png)

**Comment by Manuel-777** [comment]
This is actually on purpose, I had multiple issues tracking # of each card played, since ID within the game fluctuate it is sometimes hard to know if the card just moved between zones or if it was a new one altogether. I usually end matches with the number of , for example, nexus of fates being 20. This was an extreme scenario buy attempting to fix it would only make things worse.

My solution was to simply add cards into a list if we see them and do not count them.

**Comment by oseparovic** [comment]
Fair enough. Maybe it would cut down on reports if you put a note somewhere informing the user about this so they know it's done purposefully and isn't a bug?

**Comment by omegaula** [comment]
Can you just remove  the number altogether? This makes it clear it's a list of cards, not how many of each card.
