### ISSUE TITLE
Add Collection Filter to Explore tab

### ISSUE THREAD

**Issue by flatluigi** [Manuel-777/MTG-Arena-Tool#93]
The Explore tab is really nice, but it would be even more useful if you could filter it by decks only buildable with your collection (or, more realistically, sort decks by how few cards you'd have to acquire to build them)

**Comment by Manuel-777** [comment]
Initial implementation;
[6a4d8659f16cf57a1fcf5de63ac3e57682dd7986](https://github.com/Manuel-777/MTG-Arena-Tool/commit/6a4d8659f16cf57a1fcf5de63ac3e57682dd7986)
![image](https://user-images.githubusercontent.com/4711391/50375205-9907a280-05d8-11e9-9f9c-eea553d77c04.png)

Currently I went with the 'send collection on each request' method as it seemed the quickest way to implement it, We will see how it performs (may make requests take a little bit longer because it has to do all the filtering server-side)
