### ISSUE TITLE
Collection Cards Error

### ISSUE THREAD

**Issue by fai1984** [Manuel-777/MTG-Arena-Tool#999]
Que tal, engo la v4.0.14. En la parte de colección hay cartas que tengo y no aparecen o aparecen en menor cantidad. Muy bueno el app, gracias.

Translate: In collection tab there are cards that I own and do not show up, or show as if I have less copies of.

**Comment by fai1984** [comment]
Se actualizó y sigue igual Manuel.

**Comment by Porkepix** [comment]
Cusiouly, commons/uncommons/rares that went missing are back for me, but… I also opened today the Eldraine pack from mastery pass where I got a 3rd copy of my last missing unco and a 4th copy of a mythic. MTG-Arena-Tool see them in the economy tab and indeed show I got a new copy of each of them… but declare the new copy as 3rd and second instead of 4th and 3rd…

**Comment by fai1984** [comment]
Que tal Manuel, soy de Argentina, creo que vos también. Pasamelo por favor
en español que en inglés no te entendí ajjajaja


Francisco.

**Comment by Manuel-777** [comment]
This should be fixed now, and related to #1051 that is also fixed.
